import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#232621",
    alignItems: "center",
    justifyContent: "center",
  },
  logo: {
    //flex: 1,
    height: 150,
    width: 250,
    alignSelf: "center",
    margin: 30,
    marginTop: 70,
  },
  map: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
    height: 450,
    marginLeft: 10,
    marginRight: 10,
  },
  button: {
    backgroundColor: "#8CD4C9",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "#232621",
    fontSize: 16,
    fontWeight: "bold",
    margin: 10,
  },
  input: {
    height: 40,
    //fontSize: 16,
    //width: 300,
    borderWidth: 1,
    borderRadius: 3,
    marginTop: 20,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#e0d1a3",
    backgroundColor: "#e0d1a3",
    paddingLeft: 20,
  },
  header: {
    fontSize: 26,
    color: "#8CD4C9",
    fontStyle: "italic",
    fontWeight: "400",
    margin: 20,
    marginTop: 40,
    borderBottomColor: "#8CD4C9",
    borderBottomWidth: 3,
    alignSelf: "center",
  },
  regularText: {
    color: "#e0d1a3",
    fontSize: 18,
    margin: 5,
    //marginLeft: 10,
  },

  eventBox: {
    backgroundColor: "#e0d1a3",
    margin: 15,
    borderRadius: 10,
  },

  eventTitle: {
    color: "#232621",
    fontSize: 22,
    margin: 5,
    textAlign: "center",
    marginTop: 5,
    fontWeight: "bold",
    fontFamily: "Ubuntu-Bold",
  },

  eventLocation: {
    color: "#232621",
    fontSize: 19,
    margin: 2,
    fontFamily: "Ubuntu-Bold",
    flexDirection: "row",
    alignItems: "center",
  },

  eventDate: {
    color: "#232621",
    fontSize: 19,
    margin: 2,
    marginLeft: 10,
    fontFamily: "Ubuntu-Bold",
    alignItems: "center",
    //justifyContent: "flex-start",
  },
  picker: {
    height: 50,
    width: 100,
    color: "#e0d1a3",
    margin: 20,
    alignSelf: "center",
  },
});
